global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spark"
    static_configs:
      - targets: ["spark-master:8080"]
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
